### ISSUE TITLE
EFI Bootlooping on GA401QM

### ISSUE THREAD

**Issue by Icee666** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#10]
The latest EFI, just shows the apple logo and then the laptop reboots.

Bios version is 411 (oldest one)
R7 5800HS with RTX 3060.

I've tried the [OC ](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/issues/5) you've sent in the latest closed Issue (Uploaded on 1 September) and it willload into apple logo ( half loading) and then reboots.

**Comment by PIut02** [comment]
I think this is due to some errors in the BIOS, because OC did not provide any error logs. I have encountered some other people with similar errors before, and they solved the problem by resetting the BIOS. It has nothing to do with OC.

**Comment by Icee666** [comment]
> I think this is due to some errors in the BIOS, because OC did not provide any error logs. I have encountered some other people with similar errors before, and they solved the problem by resetting the BIOS. It has nothing to do with OC.

I just need to cross the option in Above 4G Decodin in UMAF right?

I disabled the secure and fast boot, idk where the problem is. Trying to reset bios and do it again

**Comment by Icee666** [comment]
PCI Subsystem Settings:

Above 4G Decoding       [X]
Re-size BAR Support      auto
SR-10V Support             [ ]
BME DMA Mitigation     [ ]

I've changed only this option, still same problem, one guy have same problem as me. 😢

**Comment by PIut02** [comment]
I have consulted the documentation and found that there is a very small chance that some motherboards may encounter this situation. To solve it, you need to reflash the BIOS chip. For these motherboards, you need to be careful when resetting the NVRAM.

**Comment by PIut02** [comment]
And have you tried restarting and entering Windows after resetting the NVRAM, and adding the OC boot entry?

**Comment by Icee666** [comment]
Actually I have no OS installed on my Laptop, just clean drive.
For reflashing BIOS chip, you mean download the bios from [asus](https://www.asus.com/us/supportonly/ga401qm/helpdesk_bios/) ?

I downloaded the 411 bios and flashed in asus EZ 3.

Then I inserted usb, cleaned NVRAM and then boot into the EFI.

**Comment by fierceeo** [comment]
> I think this is due to some errors in the BIOS, because OC did not provide any error logs. I have encountered some other people with similar errors before, and they solved the problem by resetting the BIOS. It has nothing to do with OC.

When enabling AppleDebug and DisableWatchDog, and changing the debug target to 67 in the config.plist, the OpenCore log is as follows:

```05:552 02:114 OC: Prelinked injection AirportItlwm.kext (V2.3.0) - Invalid Parameter
05:964 00:412 AAPL: #[EB.LD.LKFS|-?] Ok(0)
06:020 00:055 AAPL: #[EB.LD.LKC|-?] Ok(0)
06:062 00:041 AAPL: #[EB|BST:REV1]
06:101 00:038 AAPL: #[EB|CSR:OUT] 0x00000040
06:141 00:040 AAPL: #[EB.BST.FBS|+]
06:178 00:037 AAPL: #[EB.BST.FBS|ADSZ] 0
06:346 00:167 AAPL: #[EB.BST.FBS|KSSZ] 0
06:385 00:039 AAPL: #[EB|SB:SBGMFNS] j223ap.im4m
06:425 00:039 AAPL: #[EB|RH:PF] usr\standalone\OS.dmg.root_hash
06:465 00:040 AAPL: #[EB|RH:MF] <"usr\\standalone\\OS.dmg.root_hash.j223ap.im4m">
06:505 00:040 AAPL: #[EB.LD.LF|IN] 0 1 <"usr\\standalone\\OS.dmg.root_hash"> <"0">
06:549 00:043 AAPL: #[EB.LD.OFS|OPEN!] Err(0xE) <"usr\\standalone\\OS.dmg.root_hash">
06:588 00:038 AAPL: #[EB.RH.LRH|P!] Err(0xE) <- EB.LD.LF
06:643 00:055 AAPL: #[EB.BST.FBS|!] Err(0xE) <- EB.RH.LRH
06:682 00:038 AAPL: #[EB|LOG:DT] 2023-10-15T02:23:17
06:721 00:039 AAPL: #[EB|LOG:EXITBS:START] 2023-10-15T02:23:17
```
[EB|LOG:EXITBS:START] is a common issue documented in the OpenCore guide.
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start

Nevertheless, I have tried all the combinations described in the guide and have not been able to resolve this issue.

**Comment by fierceeo** [comment]
Additionally, I would like to mention that while I have the same laptop model as Icee666, I am on bios version 414.

**Comment by PIut02** [comment]
umm...that's strange, because some settings that avoid EB may affect the normal operation of other 2021 models, and they have not encountered the EB problem. Therefore, in a previous commit and issue, I removed some adjustments for the 2020 model. But now the same problem has appeared on the 2021 model. Try replacing this in the OC folder: 
[config.zip](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/files/12909186/config.zip)

**Comment by Icee666** [comment]
Tried this, now instead of rebooting it just stucks (Around 25%)

**Comment by fierceeo** [comment]
I seem to be getting the exact same error message as before.

**Comment by gkgzyx** [comment]
@fierceeo Micron's SSD?

**Comment by gkgzyx** [comment]
@fierceeo I have also encountered this issue, and after switching to a WDC's SSD, it can be installed normally.

**Comment by Icee666** [comment]
Yeah I can confirm it's an SSD issue
I have Hyinix
