### ISSUE TITLE
Is it possible to run on Rog Zephyrus G15 2021?

### ISSUE THREAD

**Issue by aswindevsp** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#14]
I have a g15 ryzen 9 5900hs. Tried booting with the efi files. It restarts after showings some logs. I tried removing the amd related kexts and patches, same issue comes up. 

Any idea how to fix this? 

![Screenshot_20231104-134756_Photos](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/40211325/f680c8d3-677b-441a-9060-8b504564f5c1)

**Comment by PIut02** [comment]
You can try this, but this repository is not maintained by me
https://github.com/Stese18/ASUS-ROG-Zephyrus-G15-EFI
