### ISSUE TITLE
Bluetooth still not working G15 2021

### ISSUE THREAD

**Issue by fgynfspl** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#16]
Hey there! I have a G15 2021, your EFI works perfectly for my setup (5900hs, 24gb ram, intel AX210), apart from Bluetooth. I tried your updated EFI, I tried updated Bluetoolfixup and BTpatchers, still not working (latest version of Ventura 16.3.1). 
Also, I enabled S3 sleep through UMAF, but trying to put the system to sleep results in a black screen that is only resolved by restarting. (I have an rtx 3070 if that is relevant here)

**Comment by PIut02** [comment]
Try to remap the USB, maybe it's because the interfaces of G14 and G15 are different.Sleep may also be related to USB.

**Comment by fgynfspl** [comment]
After much tweaking, I managed to install Monterey and sleep is working now. I need to look into USB remapping to see if that solves Bluetooth or not. Can you tell me how to do the remapping please ?

**Comment by fgynfspl** [comment]
So I read on a forum that the AX210 doesn't work in Monterey as it doesn't support bluetooth versions lower than 5.2. So the issue should be fixed by buying an intel AX200 (like you have in the original guide).
