### ISSUE TITLE
Battery life got worse on Sonoma

### ISSUE THREAD

**Issue by throwaway29292** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#18]
On my G14 2020 with GTX 1660Ti, the battery life seems to be worse on Sonoma 14.1.1 than it was on 13.6. The device only lasts around 2-3 hours at light load (AMD Power Tool shows draw of around 6-8W). 
Could possibly the dGPU disabling patch be broken?

On Ventura, the AMD Ryzen Tool sometimes showed as low as 3W on the CPU. The laptop also lasted for longer time, around 4-5 hours.

**Comment by PIut02** [comment]
你可以通过查看pci设备来检查屏蔽是否生效，如果屏蔽没有生效那么pci设备中会有英伟达相关，相反则没有。根据nootedred作者的说明，我想也许有一种更好的方法来控制功耗和温度，我会在接下来的几天内验证它

**Comment by PIut02** [comment]
Please check again.

**Comment by edwin170** [comment]
> I can confirm, that the power consumption definitely went down. I got to as low as 7,5W idle, which is only slightly worse, than windows. In web browser, I get around 9-10W, which is almost the same as in windows.
> 
> I guess the consumption might be even better in Ventura, but I don't have time to try it right now.
> 
> Thanks a lot for the EFI, it seems to work perfectly now.

soo please what did you do to fix the consumption ?
