### ISSUE TITLE
Thank you for your hard work, it works well!

### ISSUE THREAD

**Issue by imjaaee** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#20]
I have the 2020 model and it works fairly well. I don't need to disable the `NootedRed` kext while installing, everything happens smoothly and quickly.

1. For those who experience the boot loop or boot stuck, just add this boot-arg: `ncpi=0x2000`.
2. I can confirm the issues with **Chromium** browsers. I try to use **Firefox** but it freezes my PC continuously, which is bad, so never try to use this. My solution is that you could use **[Microsoft Edge](https://www.microsoft.com/en-us/edge/download)**, which has similar issues in **Chrome** but it is more stable so far in my case. It freezes for a few minutes when typing in the search bar for the first time, after that you can use it smoothly.
3. Your update for OpenCore 0.9.6 does not work with Wi-Fi in my case, I've replaced the new kexts with the old ones and it works normally.

I wanna thank you a lot for your hard work! Hopefully, the `NootedRed` team will release more stable builds soon.

<img width="1440" alt="Screenshot 2023-11-20 at 17 42 41" src="https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/62211294/7342c097-dc99-4623-9192-d6d01cc42372">

**Comment by PIut02** [comment]
Regarding the first point, if `Above 4G decoding` is turned on correctly, I don't think `ncpi=0x2000` is needed.
Regarding the second point, using these browsers only requires turning off hardware acceleration to avoid system freezing.
Regarding the third point, this update is only available for the Sonoma version, you can find the previous version [here](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/tree/Ventura), and I will update this branch if needed.
Finally, thank you for your support😊

**Comment by imjaaee** [comment]
> Regarding the first point, if `Above 4G decoding` is turned on correctly, I don't think `ncpi=0x2000` is needed. Regarding the second point, using these browsers only requires turning off hardware acceleration to avoid system freezing. Regarding the third point, this update is only available for the Sonoma version, you can find the previous version [here](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/tree/Ventura), and I will update this branch if needed. Finally, thank you for your support😊

Thank you! I also want to ask you if there is any way to make AirDrop work? I could find my iPhone via AirDrop but could not send anything. In my iPhone, I could not find my PC either. I've heard that we have to replace the current card with the native card to make it work. Thank you.

**Comment by PIut02** [comment]
Intel network cards don't make AirDrop work, some Broadcom network cards do, but I haven't learned more about it.

**Comment by imjaaee** [comment]
> Intel network cards don't make AirDrop work, some Broadcom network cards do, but I haven't learned more about it.

Thank you for your response!
