### ISSUE TITLE
Wifi is not working (with BCM4630) + can’t find EFI partition of my Ventura installed

### ISSUE THREAD

**Issue by Z2VvZ2Vv** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#21]
Hi there ! 

I have some problems with my installation, all the features works fine, but in my case enable « Above 4G decoding » (I don’t understand what is it for ?) stuck my laptop in « IOPCI Configurator Waittime is 900 Freeze ».  Maybe I have to add « ncpi=0x2000 » in the boot args ?

Also I the WiFi is not working with my AX200 and with my new BCM4630 ! I don’t know what is the issue (Bluetooth works very fine with the two WiFi card). I read that it could be a problem of USB mapping, but how I can do ? (also I can see the Bluetooth in the list of hackintool, and also the BCM4630 and I think WiFi is a problem with PCI config ?) And BCM4630 is natively supported by macOS isn’t it ?

Finally, I can’t find the EFI partition on my installed Ventura. And I don’t now if a have to create it or anything else. I do a « diskutil list » but there are 2 part : 1 for internal and 1 for data and in this there are « Preboot » maybe is this ? 

Thanks for all the helps you could give me !

**Comment by imjaaee** [comment]
1. Adding `ncpi=0x2000` may solve the problem, I don't know where to find **Above 4G Decoding** in my case either, but without `ncpi=0x2000` I could not boot.
2. Use the EFI in the Ventura branch instead because the main branch is used for Sonoma, that's why you don't have Wi-Fi. Mine is AX200 too and Wi-Fi works fine.
3. To view your EFI after installing, you have to mount your partition using **OpenCore Configurator**.

**Comment by Z2VvZ2Vv** [comment]
Ok i will change the EFI folder, it’s maybe for that but the BCM4630 is natively supported by macOS ? 

And for the EFI folder in the installed Ventura, I already check with OpenCore Configurator, it’s for that I say that « diskutil list » command don’t show the EFI partition of my installed Ventura. Have you an idea ?

**Comment by PIut02** [comment]
When using UMAF, you will find `Above 4G Decoding` in the Device Manager > PCI Subsystem Settings, I'll add detailed instructions to the README in the next update.

And if you want to use a Broadcom network card, you need to change the WIFI and Bluetooth kext. The kext of this repository is only available for Intel Network Interface Cards.

To remap usb, you can check this repository: https://github.com/USBToolBox/tool.

**Comment by PIut02** [comment]
Because the Intel network card also uses the same Bluetooth driver, so Bluetooth works, but WiFi is not the same. If your BCM model is supported, simply remove `IntelBTPatcher`, `IntelBluetoothFirmware` and `AirportItlwm` and add [AirportBrcmFixup](https://github.com/acidanthera/AirportBrcmFixup).

**Comment by Z2VvZ2Vv** [comment]
I give up, WiFi not working on macOS and Windows. And if I use the Intel card I don’t care I wanted airdrop. No problem.. I’m still sad 😩
