### ISSUE TITLE
last line ACPI: sleep states S3 S4 S5

### ISSUE THREAD

**Issue by edwin170** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#22]
hi, first thanks for this efi.

when i try to boot monterrey on an external ssd with this efi with some modifications like the serial number. this gets stuck on ACPI and reboot. do you have any idea how to fix it please

my laptop is a g14 2021. AMD Ryzen 7 5800HS with a rtx 3060. i have activated the s3 sleep, above 4g decoding, the igpu ram to 2gb. i tried without this option and this reboot continues.

https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/122418602/73b2a143-1f1a-435d-baf2-7e343a010afb

**Comment by PIut02** [comment]
if I'm not mistaken, something important should be consistent with the files under the 2021 folder in the current repository. 
With the file in #5 can you boot normally? And please tell me your internal ssd model, even if you boot from an external ssd it still has an effect.

**Comment by edwin170** [comment]
> if I'm not mistaken, something important should be consistent with the files under the 2021 folder in the current repository. 
> 
> With the file in #5 can you boot normally? And please tell me your internal ssd model, even if you boot from an external ssd it still has an effect.

It's an Intel chip one iirc, it is a kingspace. And yeah it booted up after I reset nvram with the efi above. But internet and Bluetooth are not working sadly

**Comment by edwin170** [comment]
amfi_get_out_of_my_way=1 i saw this argument, isn't this dangerous ?

**Comment by PIut02** [comment]
> amfi_get_out_of_my_way=1 i saw this argument, isn't this dangerous ?
This is just to unblock some apps that don't have a signature, and you can delete it if you don't need it.

**Comment by PIut02** [comment]
And ask if there is still a startup error with the latest files in the repository now？

**Comment by edwin170** [comment]
> And ask if there is still a boot error with the latest files in the repository now？

It stops bro into sleep thingy but with the zip efi above it worked but wifi and Bluetooth doesn't work 😭

**Comment by PIut02** [comment]
Ok, I think there may be something wrong in a certain update, I will recheck it, about wifi and bluetooth, the kext in the zip above is only for the Ventura version, other versions of the system cannot be used, to fix it only need to download the corresponding version of the kext replacement or change the system version.

**Comment by edwin170** [comment]
MediaTek Wifi-6 MT7921 also just in case this is my card

**Comment by PIut02** [comment]
MTK is unsupported and there is no way to use it in macOS, please replace the Intel network card if necessary.

**Comment by edwin170** [comment]
I changed the wifi card and wifi and bluetooth started working well. thank you so much for this efi

**Comment by edwin170** [comment]
hi, do you have any idea about this ?, I always execute sudo pmset autopoweroff 0 && sudo pmset powernap 0 && sudo pmset standby 0 && sudo pmset proximitywake 0 && sudo pmset tcpkeepalive 0 before sleep. so always it can't show anything when I want to wake it up so I had to force reboot. now after it sleep I wake it up and then connect a hdmi and I can see the screen but in my laptop I can't. it is not detecting the laptop screen after the sleep. could you please tell me if you know something about it.

**Comment by PIut02** [comment]
So, first check the USB issue and check whether the dGPU mask patch takes effect, by checking whether there is NVIDIA-related in the PCI device.

**Comment by edwin170** [comment]
any idea please ?

**Comment by PIut02** [comment]
Please view the information below in wIndow and show it to me: 
Device Manager -> Display Adapters -> dGPU -> Properties -> Details > BIOS device name

**Comment by edwin170** [comment]
> Please view the information below in wIndow and show it to me: Device Manager -> Display Adapters -> dGPU -> Properties -> Details > BIOS device name

it is the same as in the .aml PCI0.GPP0.PEGP

**Comment by edwin170** [comment]
![Screenshot 2024-03-07 at 12 23 18 PM](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/122418602/021b3c15-2761-4817-abc2-34ada86eb2fa)

and here is from macOS

**Comment by PIut02** [comment]
It looks like the patch didn't work, I think maybe 2020 and 2021 used different acpi methods, try this one: 
[SSDT-dGPU-Off.aml.zip](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/files/14527170/SSDT-dGPU-Off.aml.zip)

**Comment by edwin170** [comment]
> It looks like the patch didn't work, I think maybe 2020 and 2021 used different acpi methods, try this one: [SSDT-dGPU-Off.aml.zip](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/files/14527170/SSDT-dGPU-Off.aml.zip)

yeah bro I was looking information about this and i think I saw something about it happens when bad acpi method, let me try it and thanks

**Comment by edwin170** [comment]
it still detecting the Nvidia graphic

**Comment by PIut02** [comment]
Did you add it to the config file?

**Comment by edwin170** [comment]
> Did you add it to the config file?

Ofc and it was enabled it

**Comment by PIut02** [comment]
That is strange because so far there are only two acpi methods to mask discrete graphics cards.
Have you ever tried to clear nvram?

**Comment by edwin170** [comment]
Let me try reset nvram

**Comment by edwin170** [comment]
Nop it continue detecting the graphic

**Comment by PIut02** [comment]
请提取DSDT文件并上传，以便我查看问题在哪里

**Comment by edwin170** [comment]
> Let me try clear nvram

Do you mean dump my acpi DSDT?

**Comment by PIut02** [comment]
> Do you mean dump my acpi DSDT?

Yes.
Tips: it is best to get dsdt in windows without opencore boot, so as not to interfere with dsdt files.

**Comment by edwin170** [comment]
ok thank you bro, look i dumped it on windows 11 
[DSDT.zip](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/files/14527920/DSDT.zip)

i updated as zip because github doesn't allow me to share it

**Comment by PIut02** [comment]
Try this one:
[SSDT-GPU-DISABLE.aml.zip](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/files/14528285/SSDT-GPU-DISABLE.aml.zip)

**Comment by edwin170** [comment]
> Try this one: [SSDT-GPU-DISABLE.aml.zip](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/files/14528285/SSDT-GPU-DISABLE.aml.zip)

same, thank you for help I will look for others methods and see if I can fix it

**Comment by PIut02** [comment]
There is another way to disable dgpu by adding `-wegnoegpu` to boot-args, but this method is not complete, it only makes nvidia devices not display, actually still powered, that is, it cannot save power by this method, and sleep will have problems.

**Comment by edwin170** [comment]
> There is another way to disable dgpu by adding `-wegnoegpu` to boot-args, but this method is not complete, it only makes nvidia devices not display, actually still powered, that is, it cannot save power by this method, and sleep will have problems.

: ( so wegnoegpu will not help, as I want to save power.

**Comment by edwin170** [comment]
![Screenshot 2024-03-07 at 12 28 06 PM](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/122418602/80ac0f60-dc21-44f2-8356-8b5ca098a651)


in a SSDT7.aml file I found that, should that help ?

**Comment by edwin170** [comment]
![Screenshot 2024-03-07 at 2 40 59 PM](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/122418602/773859a3-fd62-456d-ada7-c6f801e5e778)


in a SSDT7.aml file I found that, should that help ?

**Comment by PIut02** [comment]
Maybe you should check ssdt5 because PCI0.GPP0.PEGP is in this one.

**Comment by edwin170** [comment]
> Maybe you should check ssdt5 because PCI0.GPP0.PEGP is in this one.

okey thank you
