### ISSUE TITLE
About the BFixup kext workaround for Chromium browsers

### ISSUE THREAD

**Issue by metronormalist** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#27]
Hello, I want to confirm that with the `Lilu` > `NootedRed` > `BFixup` order, my system has a boot loop and cannot start normally. When I change to `Lilu` > `BFixup` > `NootedRed` (`BFixup` is before `NootedRed`), it boots normally and Chromium browsers work great. Could you confirm that again and update your guide?

Moreover, I don't use the original `Lilu` kext (1.6.7), I use a modified version of it (1.6.6) by the author of `BFixup` and it works. I don't know if is it necessary or not but the author recommends using it along with `BFixup`. Here is the link: https://files.catbox.moe/8sj97w.zip. Thank you.

**Comment by PIut02** [comment]
In fact, the authors of `Bfixup` later used the latest lilu compilation to make `Bfixup` work on Sonoma, that's the version we're using now. So I don't think there is a need to use modified lilu.

I later tried `Lilu > BFixup > NootedRed` and found it working as well, thanks for your feedback, I will fix it in the next update.

**Comment by metronormalist** [comment]
> In fact, the authors of `Bfixup` later used the latest lilu compilation to make `Bfixup` work on Sonoma, that's the version we're using now. So I don't think there is a need to use modified lilu.
> 
> 
> 
> I later tried `Lilu > BFixup > NootedRed` and found it working as well, thanks for your feedback, I will fix it in the next update.

Thank you. That's great to hear.
