### ISSUE TITLE
Kernel boot failure

### ISSUE THREAD

**Issue by yerarassyl** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#28]
Hello Pluto, Dakinianaya. I have an issue when the kernel starts. Can you help me plz?
My laptop is ZEPHYRUS G15 GA503RM HQ067W with Ryzen 9 6900HS and Nvidia GPU. I think it's a problem with bios or something related to it because I tried a lot of ways to install Ryzentosh, and all of them with the same result. However, your efi is most compatible with my laptop. I removed airport and something for "android phone" kext. Also removed it from config.plist. I thought that the problem was with my USB stick and tried to run by SSD but nothing changed.
![photo_2024-02-04_06-41-14](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/146832990/35c299b5-ef33-495b-ae0f-53ab5124bfd9)
I can send you more files if you need them.
Best wishes)))

**Comment by PIut02** [comment]
You can check this out to fix the installation issue: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start
But I still don't recommend installing hackintosh on this laptop right now, because NootedRed doesn't support 6000 series Ryzen integrated graphics, which means that even if it can be installed successfully, it will hardly work without GPU hardware acceleration.

**Comment by yerarassyl** [comment]
> You can check this out to fix the installation issue: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start
> 
> But I still don't recommend installing hackintosh on this laptop right now, because NootedRed doesn't support 6000 series Ryzen integrated graphics, which means that even if it can be installed successfully, it will hardly work without GPU hardware acceleration.

Thank you for quick response. Is it possible to detect exact problem with debug opencore? And have you any information about next nootedred release for 6000x? Id like to prepare my EFI for future using.

**Comment by PIut02** [comment]
> Thank you for quick response. Is it possible to detect exact problem with debug opencore? And have you any information about next nootedred release for 6000x? Id like to prepare my EFI for future using.

I think you can try it first: https://dortania.github.io/OpenCore-Install-Guide/extras/kaslr-fix.html#using-devirtualisemmio
If there are still errors, just keep trying the other options of the site in the reply above
