### ISSUE TITLE
Reboots to Windows on OpenCore Boot Menu Selection 

### ISSUE THREAD

**Issue by dipliee** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#29]
With a bootable USB with the new Sonoma and your EFI, when i select the installer on the OpenCore BootMenu it starts but immediately reboots. I used MountEFI to put the EFI onto the USB. ( and not installed nootedRed, yet. can't find any guide )

**Comment by PIut02** [comment]
Please check the BIOS options

**Comment by dipliee** [comment]
Is there a guide to what my BIOS options should look like ?
i disabled secureBoot

( i have the 2020 GA401 )

**Comment by PIut02** [comment]
I have described the all options of the BIOS in detail in the README.

**Comment by dipliee** [comment]
true. I did everything that was needed with the UMAF but it still rebooted right when i pressed to install Sonoma..

**Comment by PIut02** [comment]
It could be an issue with the USB installer, maybe you should deploy OpenCore on your local hard drive.
I don't know what caused it, but this issue shouldn't be related to this EFI.

**Comment by dipliee** [comment]
can you just expand on what you mean by "deploying OpenCore on the local Hard drive" ?

**Comment by PIut02** [comment]
Just copy the OpenCore folder to the EFI partition, just like you would on a USB drive, and then use the tool to add startup items

**Comment by dipliee** [comment]
so instead of an bootable usb, i try to boot from open core on the hard drive ?

**Comment by PIut02** [comment]
> so instead of an bootable usb, i try to boot from open core on the hard drive ?

Yes
