### ISSUE TITLE
Unable to Pair Bluetooth Mouse

### ISSUE THREAD

**Issue by summertime-saga** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#33]
Pairing other devices such as earphones works fine. However, I can't pair my bluetooth mouse. Is there a workaround for this?

**Comment by PIut02** [comment]
Try this version of kext
[IntelBluetoothFirmware.zip](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/files/14505242/IntelBluetoothFirmware.zip)

**Comment by summertime-saga** [comment]
The issue still persists even with changed kext. This mouse works fine in windows tho.

**Comment by PIut02** [comment]
This is a known problem with IntelBluetoothFirmware, but according to https://github.com/OpenIntelWireless/IntelBluetoothFirmware/pull/446 this issue should be fixed, this is also the version of the file I sent above, maybe you should publish issue in IntelBluetoothFirmware for help.

**Comment by summertime-saga** [comment]
I was able to pair my bluetooth mouse by downgrading to Monterey 12.7.3 and using version 2.3.0 of IntelBluetoothFirmware. Thanks for responding tho :)
