### ISSUE TITLE
Installation issue of Sonoma 14.4

### ISSUE THREAD

**Issue by Z2VvZ2Vv** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#36]
Hi there ! I have a problem with the final part of the installation.

I already tested to reinstall it because i was that it was an installation issue, but no. For the EFI file I just use the repo and add some random product informations. 

![IMG_2672](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/62845771/f02f2177-5601-4bb5-82a8-e8199e8fc020)

![IMG_2673](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/62845771/9878a2ed-adbf-4808-9343-70e2dae387eb)

![IMG_2674](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/62845771/d68ba496-4200-4e4f-bd1b-a2267ee4529c)

![IMG_2675](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/62845771/822f438c-7ffa-43bd-a6cf-39ffb31d2320)

![IMG_2676](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/62845771/d18cd4bb-064f-4ff3-a28b-043b49fa9016)

Any ideas ?

**Comment by PIut02** [comment]
Have you disabled nootedred and used the latest repository?

**Comment by Z2VvZ2Vv** [comment]
For the repo, I downloaded the latest ! And nootedred i didn’t touch it at all so it’s maybe this. 

But why ? Because this is really the final step of the installation, the name of the part is « macOS » on OpenCore Bootloader !

**Comment by PIut02** [comment]
According to the NootedRed authors, this is a known bug in Lilu and only occurs during installation and recovery phases, and can only be avoided in this way at present.

**Comment by Z2VvZ2Vv** [comment]
Ok, so I just disable the kext (NootedRed) and I see ?

**Comment by PIut02** [comment]
> Ok, so I just disable the kext (NootedRed) and I see ?

Yes

**Comment by Z2VvZ2Vv** [comment]
Of course ! It was that ! Everything works very fine ! Thanks a lot !

**Comment by PIut02** [comment]
You're welcome

**Comment by OlamireDev** [comment]
Can anybody tell how to get mac os recovery image to show on opencore, I see windows, ubuntu but not the sonoma recovery image
