### ISSUE TITLE
Bad Performance in Safari

### ISSUE THREAD

**Issue by ngntriminh** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#42]
Hello, I want to share a problem that my Safari has a pretty bad performance compared to Chrome (after using the [NootedRed](https://github.com/htmambo/NootedRed) version by [htmambo](https://github.com/htmambo) or even the original one along with BFixup.kext, Chrome works well without any issues). I also try to disable NootedRed but Safari still performs badly. It loads websites really slowly and laggingly, especially YouTube even though Safari is a native app. It seems like there's a problem related to hardware acceleration with my Safari or whatever which I don't know how to fix it. I want to ask if anybody encounters the same problem and if you guys know how to fix it. Thank you.

This is my system specs using the latest version of NootedRed by htmambo:

<img width="276" alt="Screenshot 2024-05-21 at 19 56 01" src="https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/62211294/577a8298-f636-494c-ade6-15849bc1c44d">

**Comment by PIut02** [comment]
I don't use safari very often so I don't know much about this thing, maybe you can try add `-ChefKissInternal` to boot-args

**Comment by ngntriminh** [comment]
> I don't use safari very often so I don't know much about this thing, maybe you can try add `-ChefKissInternal` to boot-args

Thank you I'll give it a shot.
