### ISSUE TITLE
BlueTooth Headphone Microphone Issue

### ISSUE THREAD

**Issue by ngntriminh** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#43]
Hi, I'm using your current EFI and although sounds can be played normally, my BlueTooth headphone microphone automatically disconnects when I try to use it in any application. It also disconnects when I head to `Settings` > `Sound`. I don't know if this only happens to me but I fixed it by replacing your AirportItlwm with [this](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.3.0-alpha/AirportItlwm-Sonoma14.4-v2.3.0-DEBUG-alpha-4ac4c79.zip) (which is a beta release) and now it works fine. My macOS version is the latest Sonoma 14.5.

**Comment by PIut02** [comment]
In fact, you can find that the latest repository has already used the latest AirportItwm, and AirportItwm is only a network card driver and has nothing to do with Bluetooth.

**Comment by ngntriminh** [comment]
> In fact, you can find that the latest repository has already used the latest AirportItwm, and AirportItwm is only a network card driver and has nothing to do with Bluetooth.
Thank you, I figured out that this problem was caused by BlueStacks, if I don't use BlueStacks, it works fine.
