### ISSUE TITLE
Typo in instructions

### ISSUE THREAD

**Issue by james090500** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#44]
The boot argument for 4G Decoding is "ncpi=0x2000" it should be "npci" instead

**Comment by PIut02** [comment]
I did make that mistake, thanks for the feedback and corrections!

**Comment by james090500** [comment]
Thank you! Left me scratching my head for a bit on why it wouldn't boot

**Comment by PIut02** [comment]
Already fixed
