### ISSUE TITLE
音质的问题

### ISSUE THREAD

**Issue by llm2580** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#46]
我发现在黑苹果下的音质不如在win或者linux下，不知道有没有办法解决，可以通过定制声卡来解决吗？我的声卡是alc285，卡在的不会整理codec那部。

**Comment by PIut02** [comment]
可以先试下简单的更换id，如果所有id试了效果都不佳的话再尝试定制alc。
话说285应该是2021的机型吧？我手里目前并没有2021款的，如果尝试有合适的id麻烦请告诉我一下，方便我修改仓库中的config，如果没有我也可以提供定制声卡方面的帮助。

**Comment by llm2580** [comment]
> 可以先试下简单的更换id，如果所有id试了效果都不佳的话再尝试定制alc。 ![QQ_1725099800009](https://private-user-images.githubusercontent.com/39442130/363405720-359d2814-2073-4da8-b639-ca238ae738f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDA2NzYsIm5iZiI6MTcyNTEwMDM3NiwicGF0aCI6Ii8zOTQ0MjEzMC8zNjM0MDU3MjAtMzU5ZDI4MTQtMjA3My00ZGE4LWI2MzktY2EyMzhhZTczOGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEwMzI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMmRjZjRiYzE0ZmE5ZjA3MzJkMWRhNzEwNWYxZjM3NzlmYzIyY2ExMDMwYjUzMjBjZjk1OGE5MWRmZmQ3ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tfuypfYAmrVvwJm9nn3FMiX_dhby4_gs9c4mTf7Eg_E) 编辑config里面右边的那个值即可，如图里的id是33 话说285应该是2021的机型吧？我手里目前并没有2021款的，如果尝试有合适的id麻烦请告诉我一下，方便我修改仓库中的config，如果没有我也可以提供定制声卡方面的帮助。

我全试完了，只有id为66可以用，但是效果不佳，只剩定制了，但是我实在是不太会，想请你指导一下，我已经提取了codec，但是不会修正数据

**Comment by PIut02** [comment]
codec上传下我看看吧

**Comment by llm2580** [comment]
[codec.txt](https://github.com/user-attachments/files/16824463/codec.txt)

**Comment by PIut02** [comment]
[AppleALC-1.9.2-RELEASE.zip](https://github.com/user-attachments/files/17005355/AppleALC-1.9.2-RELEASE.zip)
试试这个，id33

**Comment by llm2580** [comment]
<img width="758" alt="image" src="https://github.com/user-attachments/assets/dd699ce9-bfdf-40d6-b19d-97530fdc62fa">
是错在哪部了呢？

**Comment by llm2580** [comment]
<img width="758" alt="iShot_2024-09-15_20 43 16" src="https://github.com/user-attachments/assets/b04709a7-0dcf-4e0a-992f-b78e068dd4c1">
这是我用 66 id 可行的，可能是配置上有点出入出问题了？

**Comment by PIut02** [comment]
是没有声音吗还是什么问题

**Comment by llm2580** [comment]
> 是没有声音吗还是什么问题

没有声音，麦克风也用不了，可能没识别出来

**Comment by PIut02** [comment]
发现有一个地方写错了，再试下
[AppleALC-1.9.2-RELEASE.zip](https://github.com/user-attachments/files/17006553/AppleALC-1.9.2-RELEASE.zip)

**Comment by llm2580** [comment]
[EFI.zip](https://github.com/user-attachments/files/17008069/EFI.zip)
这是我用的配置文件，3.5mm 耳机孔还是解决不了，音质还是差一点点，应该没有办法了，只能说是黑苹果的问题了，不知道可不可以用 eq 拯救但是又不太会调，我的配置文件没有你说的重启到 Windows 会用不了声音的问题，还是比较完美的，你看看有没有借鉴意义，IntelBluetoothFirmware.kext和AirportItlwm.kext放不到压缩包里太大了

**Comment by PIut02** [comment]
3.5mm耳麦应该不只是定制的问题了，应该是黑苹果的二合一插孔的插入检测问题，这方面看了很多资料都没解决。
可以听一下四个扬声器都驱动了吗，如果都驱动了那音质差一点可能是Windows有杜比音效？
可以的话方便留个联系方式详细聊下吗

**Comment by llm2580** [comment]
> 3.5mm耳麦应该不只是定制的问题了，应该是黑苹果的二合一插孔的插入检测问题，这方面看了很多资料都没解决。 可以听一下四个扬声器都驱动了吗，如果都驱动了那音质差一点可能是Windows有杜比音效？ 可以的话方便留个联系方式详细聊下吗

确实是驱动了，win下关掉杜比音效就是和现在的音质一样，但是我不理解的是linux下居然没问题，按理来说linux是没有杜比音效才对的

**Comment by llm2580** [comment]
QQ可以吧？553562688

**Comment by misaka5202** [comment]
[codec#0.txt](https://github.com/user-attachments/files/29170811/codec.0.txt)

[speaker 0x14 --0x2 0x14.txt](https://github.com/user-attachments/files/29170813/speaker.0x14.--0x2.0x14.txt)

能否帮我再定制一次？现在我多获取了一个节点指向，看看会不会效果好些？
