### ISSUE TITLE
Firefox violently crashes system

### ISSUE THREAD

**Issue by fss-hacks** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#49]
Thanks for both of your huge amount of work on this.
Unfortunately Sonoma was massively unstable so I'm using your EFI with ventura like the one I wrote for the 2020.
Every time I try to open Firefox, it bounces once then the machine locks up and restarts.
I'm not sure why this is happening at all, I tried changing the SecureBootModel from Disabled to Default and it made no difference.
Any ideas?

**Comment by PIut02** [comment]
This is caused by the patch of Bfixup, if you want to solve this problem, you can delete - bfixup in boot-args or use the official version of NootedRed.

**Comment by fss-hacks** [comment]
Thanks. I so appreciate how prompt you are. 
Let me reinstall and try it. There's a separate issue with the trackpad that so far, my EFI is better than yours with that I'll open another issue for so we keep this clean.

**Comment by fss-hacks** [comment]
In terms of SecureBootModel, I was under the impression you need to change it to Disabled when you install Sonoma, but can it be changed to Default or the correct SMBIOS after install is over?

**Comment by PIut02** [comment]
You can set the SecureBootModel back to Default after the installation is over, but it will run into problems with subsequent system updates, so I will set it to Disabled.

**Comment by fss-hacks** [comment]
Makes sense. You were correct about the NootedRed version. Any idea why photoshop 2024 is force quitting on trying to edit a png file?

Cursor issues also seem fixed rn.

**Comment by PIut02** [comment]
Check this https://github.com/NyaomiDEV/AMDFriend
