### ISSUE TITLE
Install stuck on Asus Zephyrus G14 GA401Q

### ISSUE THREAD

**Issue by mapomme1108** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#5]
Hello,

Thank you for your work

I want to install macOS Ventura on an Asus RoG Zephyrus G14 (GA401Q)

If I use your OpenCore folder, I can boot the usb installer and begin the installation 
but I always stops when there is 12 minutes left at the first part of the installation process
and I have to shutdown the computer manually.
I have tried to disable NootedRed and UTBMap but there is the same problem.
and also tried with Lilu and VirtualSMC only but it is the same.

My computer has a AMD Ryzen 7 5800HS and a Nvidia GeForce RTX 3060.

Can you help me?

Thank

Regards

**Comment by PIut02** [comment]
Which version of macOS are you using?

**Comment by mapomme1108** [comment]
Thank you for your quick answer

I did a "Reset NVRAM"

I have tried your new OpenCore folder and it stops on this line 
"ACPI : sleep state S4 S5"

Before, I have been using macOS Ventura 13.4 and macOS Ventura 13.5 on several usb keys (USB 2 and USB 3)
I will redownload images and do new installation usb keys

**Comment by PIut02** [comment]
Can you type 'powercfg /a' in the Windows terminal and give the result?it seems that the problem caused by the ssdt sleep patch I added, it is better to extract dsdt.It is better if you can provide DSDT.

**Comment by mapomme1108** [comment]
Here is the result of powercfg /a

_The following sleep states are available on this system:
     Standby (S0 Low Power Mode) Connected to Network
     Hibernate

The following sleep states are not available on this system:
     Standby (S1)
The system firmware does not support this sleep state.
This sleep state is disabled when S0 low power mode is supported.

     Standby (S2)
The system firmware does not support this sleep state.
This sleep state is disabled when S0 low power mode is supported.

     Standby (S3)
The system firmware does not support this sleep state.
This sleep state is disabled when S0 low power mode is supported.

     Hybrid mode standby
Sleep mode (S3) is not available.

     Quick Start
This action is disabled in the current system policy._

Here is a link to the DSDT.aml (I did the dump on Windows with acpidump.exe)
[https://uploadnow.io/s/e66365d0-18ac-4d78-9527-02e1181b23ad](url)

**Comment by PIut02** [comment]
It's weird,you can try disabling SSDT-GPRW in config as well as ACPI Patch GPRW to XPRW and try installing again, but I'm not sure if sleep will work, Zephyrus G14 should factory support s3 sleep but your results show no, and something is missing in DSDT.
If you need to fix sleep, please use [UMAF](https:github.com/DavidS95/Smokeless_UMAF) to adjust the sleep option to s3 and then use [SSDTTime](https:github.com/corpnewt/SSDTTime) under Windows to re-extract the DSDT, I'll check again.

**Comment by mapomme1108** [comment]
Hello,

I have tried disabling the patch and SSDT-GRPW but it does not work.

The link to UMAF does not work

Can you give me the previous version of your OpenCore folder ? I have lost it

I have tried your Monterey and Big Sur OpenCore folder but it does not work 

Thanks

**Comment by PIut02** [comment]
You can find the historical version in [the following link](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/tree/39b77a74825c4d9f9f8c2f207c41429444c7c208), I think this problem may have nothing to do with opencore, have you updated the BIOS and close the fast boot or opened the above 4g decoding with UMAF?

**Comment by mapomme1108** [comment]
The BIOS is UP to date, version 412

Fastboot IS disabled

I can't find thé UMAF tool, your link does not work

**Comment by PIut02** [comment]
It just is in the linked repository, there is a UniversalAmdFormBrowser.zip, which is it.Try [this](https://github.com/DavidS95/Smokeless_UMAF/blob/main/UMAF_BETA.zip)

**Comment by mapomme1108** [comment]
Hello,

I have adjusted the sleep option to S3 in the BIOS with UMAF
Above 4g decoding was already activated

Now I can boot the installation usb key with your latest OpenCore folder
but the error is the same : it stops when there is 12 minutes left

**Comment by PIut02** [comment]
Can you please let me know the model of your ssd hard drive?

**Comment by mapomme1108** [comment]
My ssd hard drive model is :
SSD NVMe Kingston SNV2S400G 4 To
Its firmware is : ELFK1N.1

**Comment by PIut02** [comment]
It looks like the problem is not on the ssd hard drive, there is too little information and I have a hard time understanding what the problem is.
Try this [OC.7z.zip](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/files/12294418/OC.7z.zip)

**Comment by mapomme1108** [comment]
Hello,

I have tried the OC folder you gave me but there is the same problem.

I thank you for trying to help me.

I would like to know what SSDTTime does : does it generate patched files or will I have to patch them by hand?

Thanks

**Comment by PIut02** [comment]
SSDTTime will automatically generates ssdts and patches, but I compared the files generated by the same model and found that they are exactly the same as you currently using, so I don't think the problem is on this.

**Comment by PIut02** [comment]
I recently discovered that ASUS has combined MediaTek and Intel's network cards in the 2021 G14 model. However, this particular repository only provides drivers for Intel's network card, which could be one of the reasons why it cannot be installed. 
Could you please let me know your network card model? If it happens to be a MediaTek model, you would need to replace it with an Intel network card. 
Alternatively, you can try disabling AirportItlwm, BlueToolFixup, IntelBTPatcher, and IntelBluetooth Firmware in the kexts before installing, as these are the drivers for Intel's network cards and Bluetooth.

**Comment by pointlessduffin-21** [comment]
I also have a similar laptop as his. Although mine is a R7 5800HS model and an RTX 3050 (only difference is the lower-tier dGPU). 

I have experienced the same errors as his. I even disabled IntelBluetooth, AirportItlwm, NootedRed, USB and so on but no success. I even tried Monterey rather than Ventura and it's still the same.

![image](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/70265407/7deb993d-5c16-4800-acb6-ddf9a1d84f96)

(I was required to disable them so that the installer would boot according to the logs below.)

![image](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/70265407/e17c0d0c-40af-4a5f-834f-4f063f2cc3db)

I'm trying to get to the bottom of this but I've already spent like 20 hours on this so currently, I'm attempting to mount the drive to a VM, install Monterey on there then boot from it which bypasses the Installer completely from running on the host machine.

I would be happy to provide more boot logs and installer logs in screenshot form with regard to these issues.

**Comment by PIut02** [comment]
Try this?[OC.zip](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/files/12429138/OC.zip)

**Comment by PIut02** [comment]
Have you tried adding the ssdt-cpur from this zip file to the Ventura version's repository? Please give it a try and let me know the outcome.

**Comment by LoiNguyen99** [comment]
I have the same error as these guys, but I after running windows update, I got this error. Do you know how to fix it?
![369035403_6920893911308317_4693950171025849926_n](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/37283177/2b7c9e4a-9cf4-4a72-9971-768b274187f1)

**Comment by PIut02** [comment]
I’ve noticed that Asus recently released a new version of the BIOS update. It’s important to note that when updating the BIOS, Windows Update will automatically install this update, resulting in the reset of BIOS settings. To resolve this, please make sure to recheck the Secure Boot and Above 4G Decoding options. Additionally, it is recommended to clear the NVRAM before trying again.

**Comment by PIut02** [comment]
Since I don’t have a 2021 model, I may not be able to fix this issue. Surprisingly, this problem only occurs on the 2021 version, and I’m unsure of the reason behind it. I will update the supported models in the readme and welcome anyone who manages to solve this issue to submit a pull request in the future.

**Comment by PIut02** [comment]
I have fixed several existing issues, but I don’t have a machine to test if my modifications are correct. Is there anyone available to help test if problems like freezing and installation crashes have been resolved?
[OC.7z.zip](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/files/12500596/OC.7z.zip)
Reminder: This zip file does not include Nootedred, and clear NVRAM may be necessary for the changes to take full effect.

**Comment by LoiNguyen99** [comment]
Working on my computer. That's great. Thank you. 
It fixed many problems from my EFI.

However, I got some freezes when I open chrome. It only happens when Hardware acceleration is turned on in chrome settings. Do you have the same problem?

**Comment by PIut02** [comment]
It's also a known issue, but it's caused by NootedRed so there's nothing we can do, just wait patiently for the driver to fix it.

**Comment by mapomme1108** [comment]
Hello,

Thank you for your work !

I have successfully insalled Ventura with your OC folder. 

But there is no graphics acceleration.
macOS says the graphic card is : "Monitor 7 Mo"

**Comment by PIut02** [comment]
Because I did not add Nootedred, just add Nootedred after the installation is complete

**Comment by PIut02** [comment]
Already fixed.
