### ISSUE TITLE
NootedRed Red squares on desktop

### ISSUE THREAD

**Issue by fss-hacks** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#50]
It's me again!!!:)
So this time we have what I think is AGAIN a NootedRed issue. 
It revolves around the wallpaper, first theres significant lag then the image won't change..... eventually the image does change but its covered in red square graphic distortion.
Theres similar issues with the graphics picker that lets you choose your user photo.

I also noticed weird processing slowdowns with my modified version of your EFI; the only thing I changed was the NootedRed to the official distro.

**Comment by PIut02** [comment]
You should read the readme, the modified version not only adds the bfixup patch but also the VCN patch that has been removed by NootedRed, so switching back to the official version will cause the VCN to fail. I suggest removing -bfixup in boot-args to control the enablement of the bfixup patch.

**Comment by fss-hacks** [comment]
I did that long ago to get Firefox to work.
This is something new that just started appearing today. Im not at all sure what’s going on but I can tell you OCAT had a bunch of updated kext versions when I ran it on your EFI.
I ran the EFI with both the updated versions and the old versions and I’m still getting the distortion.

**Comment by PIut02** [comment]
It's weird, because there is no such problem at all, maybe you should report this to the Nootedred official

**Comment by fss-hacks** [comment]
So the red squares have never been reported to them but the login photo and wallpaper issues have and have existed for as long as Sonoma.

I really hate Sonoma as an OS. It’s hard on the machine for no reason, it has too many incompatibilities, and the gui offends my sensitivities. Ventura I can handle and it seems to be happier on the G14

**Comment by PIut02** [comment]
Sonoma does have a lot of issues. There are reports that the wallpaper problem has been improved on Sequoia, but I haven't tried it because of the wifi issue.

**Comment by fss-hacks** [comment]
I have some extremely good news for you.
With my personal tweaks and some version changes, Ventura is 100% completely functional to the limit of what is possible considering the hardware constraints etc.
I'll be posting the EFI on my github, if you want to you can take a look at it.
BTW why would imessage specifically not work in sonoma but work in ventura with zero modification?

**Comment by PIut02** [comment]
Maybe it's because of this issue https://github.com/OpenIntelWireless/itlwm/issues/990#issuecomment-2211764704
