### ISSUE TITLE
Error: Timezone & Black screen when wake on sleep

### ISSUE THREAD

**Issue by dangdd2003** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#51]
I have the model 2021 already done Hackintosh along with dual boot window. However, i current have the issue with time zone sync on macos and wake on sleep. What ever i did, even added universal real time in registry (window), it still failed to work. I have enabled s3 sleep using UMAF and add some ACPI to disable discrete card in as document on opencore website, it still failed. Do you have any suggestion for fixing these stuff.

**Comment by PIut02** [comment]
For time zones, usually just add the registry, I don't know how much more, and OpenCore doesn't have anything to do with system time zones, so I don't think this problem has anything to do with opencore.
For sleep, please try this, note please backup your original opencore folder
[OC.zip](https://github.com/user-attachments/files/17269084/OC.zip)

**Comment by dangdd2003** [comment]
I tried this new oc and config, it stucked at boot logo (i disabled verbose), dont know ưhy even i use your efi, the same problem happened

**Comment by PIut02** [comment]
What does black screen mean? You need to give me the logs so I can analyze why.

**Comment by dangdd2003** [comment]
So the problem is when i hit sleep button, the system suspended, and when i click any keys, or touchpad, the system wake on boot, but it didnt shown any thing, just only a black screen, and even no logs

**Comment by dangdd2003** [comment]
yes, i configured it so it works properly

![image](https://github.com/user-attachments/assets/c70ea489-89a4-4d76-807f-19b7fe7ea897)

**Comment by oceanthedev** [comment]
> I have the model 2021 already done Hackintosh along with dual boot window. However, i current have the issue with time zone sync on macos and wake on sleep. What ever i did, even added universal real time in registry (window), it still failed to work. I have enabled s3 sleep using UMAF and add some ACPI to disable discrete card in as document on opencore website, it still failed. Do you have any suggestion for fixing these stuff.

Maybe you can try replacing your current `NootedRed` kext with the latest version on the official [repo](https://github.com/ChefKissInc/NootedRed/releases). It seems like the dev has made some changes to fix those issues. In addition, after using UMAF to enable S3 sleep, have you executed those commands in Terminal?
```
sudo pmset autopoweroff 0
sudo pmset powernap 0
sudo pmset standby 0
sudo pmset proximitywake 0
sudo pmset tcpkeepalive 0
```

**Comment by dangdd2003** [comment]
Thanks. I have done all of theme. However, that didn’t work. Anyway, i saw that many people got this issue. I think time is needed for optimization.
