### ISSUE TITLE
Kernel panic when booting installer due to IONVMeFamily

### ISSUE THREAD

**Issue by robbins** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#54]
I get the following kernel panic when booting the installer.
![image](https://github.com/user-attachments/assets/5082488f-20b5-4946-94d2-496fadbfff8f)

My SSD is the SK hynix Gold P31/BC711/PC711.

From a quick search it seems that it might not be supported? Does Asus ship G14s with different SSDs depending on region? Supposedly a firmware update fixes it, but I get an error updating the firmware.

**Comment by PIut02** [comment]
Some ssd of hynix is indeed unsupported, and this issue should not be firmware related.
I'm not sure about mixing ssd in different regions.

**Comment by robbins** [comment]
Which SSD is in your machine?

The reason I mention firmware is due to this post: https://www.reddit.com/r/hackintosh/comments/oswepm/anybody_with_experience_with_sk_hynix_p31_nvme/

and my drive has firmware revision 41000C20, not 41062C20. 

I've tried to update the firmware to this version in Linux with nvme-cli, in Windows, in a Linux live ISO, in a WinPE live ISO, but it either fails with an error or succeeds but the firmware isn't actually updated.

**Comment by PIut02** [comment]
I am using WD SN570.
