### ISSUE TITLE
Large screen recording file size

### ISSUE THREAD

**Issue by oceanondawave** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#56]
Whenever I record my screen, I see that it takes up many GBs even though it's just a 10 seconds video. It should take around 10+ MB normally. I think that this problem is related to VCN, but `-ChefKissInternal` was included by default in the boot-args. Can this problem be resolved?

Update: I usually solve this by adding the original NootedRed and BFixup kexts while still keeping `-ChefKissInternal` and the `-bfixup` is not needed anymore. I don't know why your modified NootedRed kext is not working fine for VCN.

**Comment by PIut02** [comment]
Note that the original NootedRed removed vcn support, so `-ChefKissInternal` has no effect. Based on your results, the problem should be on vcn, and there's nothing else I can do until NootedRed authors solve the problem.
