### ISSUE TITLE
Stuck at PCI configuration begin

### ISSUE THREAD

**Issue by VoidGreatEmperor** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#8]
I get stuck on [PCI configuration begin] on my G14 2021. I don't know what to do to fix it. Please tell me if you need anything to supply.

**Comment by PIut02** [comment]
Try this version: https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/tree/36fbeb5efd2dfe78391487e8c3fa68da47be49da
Reminder: Clear NVRAM may be necessary for the changes to take full effect.

**Comment by VoidGreatEmperor** [comment]
I tried it too before but did not work.

**Comment by PIut02** [comment]
Have you already enabled Above 4G decoding using the [UMAF](https://github.com/DavidS95/Smokeless_UMAF/) tool?

**Comment by VoidGreatEmperor** [comment]
Yes, I did.

**Comment by PIut02** [comment]
Try replacing this files under this OC folder: 
[config.zip](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/files/12898577/config.zip)

**Comment by VoidGreatEmperor** [comment]
Tried it, no luck.

**Comment by PIut02** [comment]
Well, what about this: [OC](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/files/12500596/OC.7z.zip).

**Comment by ryebread5** [comment]
I have the same 2020 model as you, and I also have this error.

**Comment by VoidGreatEmperor** [comment]
This time it is a kernel panic due to NVME. I use an intel AX200 wifi card and an SKHynix NVME SSD.
![WhatsApp Image 2023-10-14 at 11 29 48_45de9fdb](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/108994678/fe9d8909-6500-488a-aeb1-b7c63a620388)

**Comment by PIut02** [comment]
Well, as I know, some SKHynix SSDs may have this error. Perhaps you need to replace the SSD to avoid it.

**Comment by ryebread5** [comment]
![IMG_1819](https://github.com/PIut02/ROG-Zephyrus-G14-GA401-Hackintosh/assets/147824144/0be18c47-a26b-40ae-8746-63c6f3a5bf59)
Odd, I still get the same error throughout these 3 different versions.

**Comment by PIut02** [comment]
> ![IMG_1819](https://user-images.githubusercontent.com/147824144/275174237-0be18c47-a26b-40ae-8746-63c6f3a5bf59.jpg) Odd, I still get the same error throughout these 3 different versions. I am using everything that comes originally in the zephyrus g14 2020 model, micron ssd & ax200 wifi card.

Bro, I think this is also a problem caused by the SSD. According to [Dortania](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-rtc-pci-configuration-begins-previous-shutdown-hpet-hid-legacy) and https://github.com/dortania/bugtracker/issues/192, the Micron 2200V used in the g14 is not on the supported list.

**Comment by ryebread5** [comment]
So what one do you have? I've got a couple of samsung & kingston ones lying around I will try.

**Comment by PIut02** [comment]
I am using the Western Digital SN570. It should be noted that some Samsung SSDs also have problems during boot, such as the PM981.

**Comment by ryebread5** [comment]
I got it fixed & installed it onto a HDD connected to a usb to sata adapter. it was so slow, so the problem is the SSD that doesn't work. Thanks for your work. :)
